version: "3"
services:
  dotnetweb:
    image: "dotnetweb:latest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    networks:
      - netcore-dev
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    expose:
      - 5432
    networks:
      - netcore-dev
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always

  redis:
    image: redis
    container_name: redis
    volumes:
      - redis-data:/data
    ports:
       - ${REDIS_PORT}:6379
    expose: 
       - 6379
    networks:
      - netcore-dev
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
  postgres-data:

networks:
  netcore-dev: